### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: library "libcamera2ndk.so" not found

### ISSUE THREAD

**Issue by ZoneLai** [yge58/caffe2-opencv-ndkcamera#1]
AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.sample.textureview, PID: 21358
                                                                        java.lang.UnsatisfiedLinkError: dlopen failed: library "libcamera2ndk.so" not found
                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:384)
                                                                            at java.lang.System.loadLibrary(System.java:1086)
                                                                            at com.sample.textureview.ViewActivity.<clinit>(ViewActivity.java:302)
                                                                            at java.lang.Class.newInstance(Native Method)
                                                                            at android.app.Instrumentation.newActivity(Instrumentation.java:1070)
                                                                            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2342)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2504)
                                                                            at android.app.ActivityThread.access$900(ActivityThread.java:165)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:150)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5546)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
11-13 16:31:27.405 21358-21358/com.sample.textureview I/Process: Sending signal. PID: 21358 SIG: 9

**Comment by yge58** [comment]
Hi,
Thank you for reporting issue.
Could you please run https://github.com/googlesamples/android-ndk/tree/master/camera first?

If the same error occurs again, maybe it is because of android version.

Thanks,

**Comment by yge58** [comment]
And please notice that, since android 7.0,  loading dynamic library (*.so) except android prebuild is forbidden.

There is no workaround. 

In your case, it is strange to see " dlopen failed: library "libcamera2ndk.so" not found ", because libcamera2ndk is prebuild in android. 

Please let me know 

Thanks
